### ISSUE TITLE
test_example_tls_toml_startup and other integration tests are flapping

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#241]
```console
---- test_example_tls_toml_startup stdout ----
	using server src path: .
running test...
using server src path: .
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:466 adding a new I/O source
sending request
2017-10-18T07:58:22.507882300+00:00 DEBUG trust_dns_proto::dns_handle:482 querying: www.example.com. A
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 56900 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184764892 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:404 consuming notification queue
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:307 loop process - 3 events, Duration { secs: 0, nanos: 238800 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 19900 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184767692 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 351500 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 14200 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184771567 }
2017-10-18T07:58:22.507882300+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 43900 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 13508400 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184907289 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 87500 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 11200 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184908494 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 4017700 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 16800 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184949080 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 46900 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 2492000 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184974675 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 80000 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 10100 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184975788 }
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::dns_handle:220 got message from receiver
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:525 added a timeout: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::dns_handle:276 sending message id: 9371
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:288 sending message len: 44 to: 127.0.0.1:54051
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 768500 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 15600 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184983874 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 44800 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 1416400 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184998684 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 78000 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 10200 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16184999771 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:530 updating a timeout: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:328 in ReadTcpState::LenBytes: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:336 got length: 103
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:340 move ReadTcpState::Bytes: 103
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 265500 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 14300 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185002787 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 56800 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 62600 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185004185 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 76300 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 9300 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185005248 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:530 updating a timeout: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:364 in ReadTcpState::Bytes: 103
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:371 reset ReadTcpState::LenBytes: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:385 returning bytes
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:396 returning buffer
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::rr::record_data:682 reading A
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::rr::record_data:723 reading NS
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::rr::record_data:739 reading OPT
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor::timeout_token:53 cancel timeout 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:548 cancel a timeout: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 544900 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 15000 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185011077 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:307 loop process - 2 events, Duration { secs: 0, nanos: 46200 }
got response: true
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:466 adding a new I/O source
sending request
2017-10-18T07:58:22.523508200+00:00 DEBUG trust_dns_proto::dns_handle:482 querying: www.example.com. A
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 28100 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185017851 }
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 0
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.523508200+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 3 events, Duration { secs: 0, nanos: 222100 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 14500 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185020428 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 255900 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 13500 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185023335 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 43900 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 8122300 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185105194 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 78100 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 9900 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185106277 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 2794100 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 14900 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185134611 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 44900 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 1818400 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185153440 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 76800 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 9400 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185154502 }
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::dns_handle:220 got message from receiver
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:525 added a timeout: 0
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::dns_handle:276 sending message id: 1566
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:288 sending message len: 44 to: 127.0.0.1:54051
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 511400 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 16200 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185160015 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 47800 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 1053200 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185171237 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 79400 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 10500 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185172344 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:530 updating a timeout: 0
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:328 in ReadTcpState::LenBytes: 0
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:336 got length: 103
2017-10-18T07:58:22.539133400+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:340 move ReadTcpState::Bytes: 103
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 260700 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 13400 }
2017-10-18T07:58:22.539133400+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185175301 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 54800 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 62200 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185176694 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:399 notifying a task handle
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 74400 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 9300 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185177732 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:530 updating a timeout: 0
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:364 in ReadTcpState::Bytes: 103
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:371 reset ReadTcpState::LenBytes: 0
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:385 returning bytes
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::tcp::tcp_stream:396 returning buffer
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::rr::record_data:682 reading A
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::rr::record_data:723 reading NS
2017-10-18T07:58:22.554758100+00:00 DEBUG trust_dns_proto::rr::record_data:739 reading OPT
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor::timeout_token:53 cancel timeout 0
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:548 cancel a timeout: 0
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:499 scheduling direction for: 1
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:510 blocking
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:307 loop process - 1 events, Duration { secs: 0, nanos: 463500 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:283 loop poll - Duration { secs: 0, nanos: 13800 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:284 loop time - Instant { t: 16185182721 }
2017-10-18T07:58:22.554758100+00:00 DEBUG tokio_core::reactor:307 loop process - 2 events, Duration { secs: 0, nanos: 44500 }
got response: true
test completed
thread 'test_example_tls_toml_startup' panicked at 'join failed: Any', src\libcore\result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   1: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   2: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   3: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:572
   4: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   5: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   6: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   7: core::result::unwrap_failed<alloc::boxed::Box<Any>>
             at C:\projects\rust\src\libcore\macros.rs:41
   8: core::result::Result<(), alloc::boxed::Box<Any>>::expect<(),alloc::boxed::Box<Any>>
             at C:\projects\rust\src\libcore\result.rs:799
   9: z_named_tests::server_harness::named_test_harness<closure,()>
             at .\tests\server_harness\mod.rs:138
  10: z_named_tests::test_example_tls_toml_startup
             at .\tests\z_named_tests.rs:148
  11: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:141
  12: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panicking.rs:476
  13: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:99
```

**Comment by briansmith** [comment]
I saw this happening on Travis CI too, so I don't think it's a Windows-specific issue.

**Comment by bluejekyll** [comment]
The server test harness has some general issues I think:

`thread 'test_dnssec_restart_with_update_journal' panicked at 'assertion failed: found', server/tests/server_harness/mod.rs:114:5`
