### ISSUE TITLE
Crash when creating journal from zone with allow_update=true 

### ISSUE THREAD

**Issue by apexo** [bluejekyll/trust-dns#44]
```
2016-09-08T12:50:34.387565536+00:00 INFO named:115 loading zone file: "src/config/test/example.com.zone"`
2016-09-08T12:50:34.416164124+00:00 INFO named:129 enabling journal: "src/config/test/example.com..jrnl"
2016-09-08T12:50:34.417395558+00:00 INFO trust_dns::authority::authority:156 persisting zone to journal at SOA.serial: 199609203
thread '<main>' panicked at 'schema version mismatch, schema_up() resolves this', src/authority/persistence.rs:58
stack backtrace:
   1:     0x55d0d4c23c3f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x55d0d4c2699b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x55d0d4c26623 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x55d0d4c1852d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x55d0d48ff737 - std::panicking::begin_panic::h4c14e704ed94392f
                        at src/libstd/panicking.rs:328
   6:     0x55d0d4979704 - trust_dns::authority::persistence::Journal::insert_record::h7a7e1920fda45865
                        at /home/apexo/ext/dev/ext/trust-dns/<std macros>:3
   7:     0x55d0d4979130 - trust_dns::authority::authority::Authority::persist_to_journal::h05d78c5d49a01b1a
                        at src/authority/authority.rs:159
   8:     0x55d0d48d76a6 - named::load_zone::hd2498ba4e50bc526
                        at src/named.rs:138
   9:     0x55d0d48e7b93 - named::main::h1c8ee60b18765fac
                        at src/named.rs:225
  10:     0x55d0d4c26268 - std::panicking::try::call::hbbf4746cba890ca7
  11:     0x55d0d4c30aeb - __rust_try
  12:     0x55d0d4c30a8e - __rust_maybe_catch_panic
  13:     0x55d0d4c25d0e - std::rt::lang_start::hbcefdc316c2fbd45
  14:     0x55d0d48f7a29 - main
  15:     0x7fa51e4992b0 - __libc_start_main
  16:     0x55d0d48d5569 - _start
  17:                0x0 - <unknown>
```

**Comment by bluejekyll** [comment]
I wonder if there's another big here. It looks like the journal filename is wrong, is it possible that the new journal is empty?

How did you produce this problem?

**Comment by apexo** [comment]
I just used the example config src/config/test/example.toml with the following extra zone:

[[zones]]
zone = "example.com"
zone_type = "Master"
file = "example.com.zone"
allow_update = true

**Comment by apexo** [comment]
Before the crash, the journal file does not exist. After the crash, it exists with size 0.

**Comment by bluejekyll** [comment]
Ok, mind fixing another two lines in this? on:

https://github.com/bluejekyll/trust-dns/blob/master/src/named.rs#L94

the set_extension(".jrnl") should be set_extension("jrnl")
and similarly set_extension(".key") should be set_extension("key")

I don't know how I missed that, but I know that I don't have startup tests on the binary. I need to go back and add those. Anyway, if you could make those other changes too that would be awesome. Otherwise I'll do that later.

**Comment by apexo** [comment]
Will do.

**Comment by bluejekyll** [comment]
Thanks for the changes!
